modLoader="javafml"
loaderVersion="[12,)"
license="MIT"
[[mods]]
modId="canvasstudio"
version="2.1.2"
displayName="Canvas Studio+"
authors="SuprixZ"
logoFile="canvas-studio-icon.png"
description='''Draw, import and save paintings. Match your drawing to the nearest Minecraft inventory items with an offline visual matcher.
- made by SuprixZ'''
[[dependencies.canvasstudio]]
modId="neoforge"
type="required"
versionRange="[26.3-alpha,26.4-alpha)"
ordering="NONE"
side="BOTH"
[[dependencies.canvasstudio]]
modId="minecraft"
type="required"
versionRange="[26.3]"
ordering="NONE"
side="BOTH"
